#pragma once

#include <c10/core/Device.h>
#include <c10/core/Stream.h>
#include <c10/util/Exception.h>

#include <cstdint>
#include <functional>
#include <future>
#include <utility>

// Forward declarations
namespace c10_neuron {
struct NeuronStorageImpl;
}

namespace at::neuron {

// Forward declarations
class NeuronEvent;
struct OperationContext;
struct OperationContextResult;
struct StreamImpl;

/**
 * A Neuron stream is a linear sequence of execution that belongs to a specific
 * device, independent from other streams.
 */
class NeuronStream {
 public:
  enum Unchecked { UNCHECKED };

  explicit NeuronStream(c10::Stream stream) : stream_(stream) {
    TORCH_CHECK(stream_.device_type() == c10::DeviceType::PrivateUse1);
  }
  explicit NeuronStream(c10::StreamId stream_id, c10::DeviceIndex device_index, Unchecked)
      : stream_(c10::Stream(c10::Stream::UNSAFE,
                            c10::Device(c10::DeviceType::PrivateUse1, device_index), stream_id)) {}

  NeuronStream() : stream_(getDefaultStream().unwrap()) {}

  // Copy constructor - creates a new stream reference to the same underlying stream
  NeuronStream(const NeuronStream& other) : stream_(other.stream_) {}

  // Copy assignment
  NeuronStream& operator=(const NeuronStream& other) {
    if (this != &other) {
      stream_ = other.stream_;
    }
    return *this;
  }

  // Move constructor
  NeuronStream(NeuronStream&& other) noexcept : stream_(std::move(other.stream_)) {}

  // Move assignment
  NeuronStream& operator=(NeuronStream&& other) noexcept {
    if (this != &other) {
      stream_ = std::move(other.stream_);
    }
    return *this;
  }

  bool operator==(const NeuronStream& other) const noexcept { return stream_ == other.stream_; }
  bool operator!=(const NeuronStream& other) const noexcept { return stream_ != other.stream_; }

  /// Get the device index
  c10::DeviceIndex device_index() const { return stream_.device_index(); }

  /// Get the stream ID
  c10::StreamId id() const { return stream_.id(); }

  /// Get the device
  c10::Device device() const { return stream_.device(); }

  /// Get the underlying c10::Stream
  c10::Stream unwrap() const { return stream_; }

  /// Get the priority of this stream
  int priority() const;

  /// Check if all work submitted to this stream has completed
  bool query() const;

  /// Wait for all work submitted to this stream to complete
  void synchronize();

  /// Make this stream wait for an event
  void wait_event(const NeuronEvent& event) const;

  /// Make this stream wait for another stream
  void wait_stream(const NeuronStream& other) const;

  DeviceType device_type() const {
    return c10::DeviceType::PrivateUse1;  // 'neuron'
  }

  operator c10::Stream() const { return unwrap(); }

  struct c10::StreamData3 pack3() const { return stream_.pack3(); }

  // Unpack a CUDAStream from the 3 fields generated by pack().
  static NeuronStream unpack3(StreamId stream_id, DeviceIndex device_index,
                              DeviceType device_type) {
    return NeuronStream(Stream::unpack3(stream_id, device_index, device_type));
  }

  /// Get the default stream for a device
  static NeuronStream getDefaultStream(c10::DeviceIndex device_index = -1);

  /// Get the current stream for a device
  static NeuronStream getCurrentStream(c10::DeviceIndex device_index = -1);

  /// Set the current stream for a device
  static void setCurrentStream(const NeuronStream& stream);

  /// Create a new stream on a device
  static NeuronStream createStream(c10::DeviceIndex device_index = -1, int priority = 0);

  /// Submit an event signal primitive to this stream
  void SubmitEventSignal(const NeuronEvent& event) const;

  /// Submit an event wait primitive to this stream
  void SubmitEventWait(const NeuronEvent& event) const;

 private:
  StreamImpl* get_stream_impl() const;

  c10::Stream stream_;
};

/// Get the current Neuron stream for a device
NeuronStream getCurrentNeuronStream(c10::DeviceIndex device_index = -1);

/// Get the default Neuron stream for a device
NeuronStream getDefaultNeuronStream(c10::DeviceIndex device_index = -1);

/// Set the current Neuron stream for a device
void setCurrentNeuronStream(const NeuronStream& stream);

/// Get the current device index
c10::DeviceIndex current_device();

/// Synchronize all streams on a device
void synchronize(c10::DeviceIndex device_index = -1);

/// Submit an operation context to the asynchronous execution.
/// @param stream The stream to submit the operation to
/// @param operation_context The operation to execute
void SubmitOperationContext(const NeuronStream& stream,
                            std::unique_ptr<OperationContext> operation_context);

/// Stream pool configuration
constexpr int kStreamPoolSize = 3;
constexpr int kMaxDevices = 128;

/// Initialize all stream pools (called by NeuronResourceManager)
void InitializeStreamPools();

/// Cleanup stream pools (called by NeuronResourceManager destructor)
void CleanupStreamPools();

/// Direct stream accessors for performance-critical paths
StreamImpl* GetDefaultStreamImpl(c10::DeviceIndex device_index);
StreamImpl* GetPoolStreamImpl(c10::DeviceIndex device_index, int pool_index);

/// Iterate through all streams on a device with a callback
/// @param device_index The device to iterate streams on
/// @param callback Function to call for each stream. Return true to stop iteration.
void ForEachStreamImpl(c10::DeviceIndex device_index,
                       const std::function<bool(StreamImpl*)>& callback);

}  // namespace at::neuron
