#loc1 = loc("x")
module @jit__lambda attributes {jax.uses_shape_polymorphism = false, mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<i32> loc("x")) -> (tensor<i32> {jax.result_info = "result"}) {
    %c = stablehlo.constant dense<1> : tensor<i32> loc(#loc)
    %0 = stablehlo.add %arg0, %c : tensor<i32> loc(#loc31)
    return %0 : tensor<i32> loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc = loc(unknown)
#loc2 = loc("<ipython-input-29-4c0df9d1601b>":1:18 to :23)
#loc3 = loc("<ipython-input-31-aaeb87f28bed>":1:4 to :35)
#loc4 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/core/interactiveshell.py":3699:20 to :69)
#loc5 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/core/interactiveshell.py":3639:19 to :64)
#loc6 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/core/interactiveshell.py":3394:29 to 3395:85)
#loc7 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/core/async_helpers.py":128:8 to :23)
#loc8 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/core/interactiveshell.py":3171:21 to :33)
#loc9 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/core/interactiveshell.py":3116:25 to 3118:17)
#loc10 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py":1005:20 to :59)
#loc11 = loc("/shared_new/fhaolin/workplace/torch-eager/torch-eager/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py":1012:16 to :31)
#loc12 = loc("<lambda>"(#loc2))
#loc13 = loc("<module>"(#loc3))
#loc14 = loc("InteractiveShell.run_code"(#loc4))
#loc15 = loc("InteractiveShell.run_ast_nodes"(#loc5))
#loc16 = loc("InteractiveShell.run_cell_async"(#loc6))
#loc17 = loc("_pseudo_sync_runner"(#loc7))
#loc18 = loc("InteractiveShell._run_cell"(#loc8))
#loc19 = loc("InteractiveShell.run_cell"(#loc9))
#loc20 = loc("TerminalInteractiveShell.interact"(#loc10))
#loc21 = loc("TerminalInteractiveShell.mainloop"(#loc11))
#loc22 = loc(callsite(#loc20 at #loc21))
#loc23 = loc(callsite(#loc19 at #loc22))
#loc24 = loc(callsite(#loc18 at #loc23))
#loc25 = loc(callsite(#loc17 at #loc24))
#loc26 = loc(callsite(#loc16 at #loc25))
#loc27 = loc(callsite(#loc15 at #loc26))
#loc28 = loc(callsite(#loc14 at #loc27))
#loc29 = loc(callsite(#loc13 at #loc28))
#loc30 = loc(callsite(#loc12 at #loc29))
#loc31 = loc("jit(<lambda>)/add"(#loc30))
